// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osstlpyfzvzjjcrdayvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zc3RscHlmenZ6ampjcmRheXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTcxNTEsImV4cCI6MjA2MDkzMzE1MX0.jVggDyfad3x6-4UC_cmHdjt1YA8tramIKwIJd8fx-Is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);